# Generated by Django 4.1.1 on 2023-12-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                ('stay', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
